spring.application.name=video-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# multipart config
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.port=8082

# AWS config
aws.access-key="${AWS_ACCESS_KEY:}"
aws.secret-key="${AWS_SECRET_KEY:}"
aws.region="${AWS_REGION:}"

aws.s3.bucket-name=netflix-streaming-videos-528730633309-eu-north-1-an

# actuator
management.endpoints.web.exposure.include=health, info
